MDBoxLayout:
    orientation: 'vertical'

    MDScreen:
        MDRectangleFlatButton:
            text: "Alert Popup"
            pos_hint: {"center_x":.5, "center_y":.5}
            text_color: "white"
            line_color: "red"
            on_release: app.show_alert_dialog()

        MDLabel:
            id: my_label
            text: "Some Stuff"
            pos_hint: {'center_x': .95, "center_y": .4}
