ScrollView:
    MDList:
        TwoLineListItem:
            id: item1
            text: "Awsome list #1"
            secondary_text: "Second Line"
            tertiary_text: "Third text"
            on_release: app.presser(self, "item1")
        TwoLineListItem:
            id: item2
            text: "Awsome list #2"
            secondary_text: "Second Line"
            tertiary_text: "Third text"
            on_release: app.presser(self, "item2")